options:
  replica_set_name:
    type: string
    description: Name of the replica set
    default: rs0
  autodelete:
    type: boolean
    description: Delete database if relations are removed
    default: true

